@startuml

!theme crt-amber
skinparam actorStyle Hollow
left to right direction

:Administrateur: as A
:Stagiaire: as STA

(Interventions) as I
(Types d'interventions) as TI
(Equipements) as EQ
(Contenants) as CO
(Fluides) as F
(Types de fluides) as TF
(Accessoires) as AC
(Groupes d'utilisateurs) as GU
(Utilisateurs) as U
(Gestion\najout, modification,\nsuppression) as G
(Consultation) as C
(Saisie) as S

A -|> G
A -|> C
A -|> S
STA -|> C
STA -|> S
G ..> I: (suppression\nseulement)
C --> I
S --> I
G --> TI
G --> EQ
G --> CO
G --> F
G --> TF
G --> AC
G --> GU
G --> U

@enduml
